version: '3'
services:
  master_database:
    image: postgres
    volumes:
      - ./volumes/master_postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: reginaldo
      POSTGRES_DB: tenancy
    ports:
      - '5432:5432'

  mailhob:
    image: mailhog/mailhog:latest
    ports:
      - '8025:8025'

  redis:
    image: redis:5-alpine
    volumes:
      - ./volumes/redis:/data

  admin:
    image: ambientum/php:latest-nginx
    volumes:
      - ./admin:/var/www/app

  tasks:
    build:
      context: ./service-tasks
      dockerfile: Dockerfile.dev
    volumes:
      - ./service-tasks:/app
      - /app/node_modules
    depends_on:
      - master_database
      - admin
    env_file:
      - ./service-tasks/.env

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - nginx

  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - '80:80'